apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jf7ve9k7n-dotnet-basic
  janus-idp.io/tekton: jf7ve9k7n-dotnet-basic
  backstage.io/kubernetes-id: jf7ve9k7n-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jf7ve9k7n-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
